### Get
GET http://localhost:3000/notas
### Get for id
GET http://localhost:3000/notas/65d345be8375807c95d9df5d
### Post 
POST http://localhost:3000/notas
Content-Type: application/json

{
    "title": "Nota de nuevo",
    "autor": "UnCompa",
    "content": "Lorem ipsum akdioasjod",
    "important": true
}

### Put
PUT http://localhost:3000/notas/65d345be8375807c95d9df5d
### Delete
DELETE http://localhost:3000/notas/65d38b68763aebb2c9badc03