### Get
GET http://localhost:3000/notas
### Get for id
GET http://localhost:3000/notas/65ccb7e031606a729a2e5f9a
### Post 
POST http://localhost:3000/notas
Content-Type: application/json

{
    "title": "Haciendo Backend",
    "content": "Practicando",
    "important": true
}