### Get
GET http://localhost:3000/notas
### Get for id
GET http://localhost:3000/notas/65ce0d47f831bc2e51c8ccad
### Post 
POST http://localhost:3000/notas
Content-Type: application/json

{
    "title": "Probando todo :D de nuevo",
    "content": "Lorem ipsum akdioasjod",
    "important": true
}

### Put
PUT http://localhost:3000/notas/65ce0d47f831bc2e51c8ccad
Content-Type: application/json

{
    "title": "Prueba numero 2",
    "content": "Practicando",
    "important": true
}